# Generated by Django 3.1 on 2020-10-11 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('tipoPago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('vehiculo', models.CharField(max_length=10)),
                ('valorpagar', models.FloatField(db_column='valorPagar')),
                ('cliente', models.ForeignKey(db_column='cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente')),
                ('tipopago', models.ForeignKey(db_column='tipoPago', on_delete=django.db.models.deletion.DO_NOTHING, to='tipoPago.tipodepago')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
    ]
