# Generated by Django 3.1 on 2020-10-11 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipoVehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomvehiculo', models.CharField(db_column='nomVehiculo', max_length=20)),
                ('preciovehiculo', models.FloatField(db_column='precioVehiculo')),
                ('tipo', models.ForeignKey(db_column='tipo', on_delete=django.db.models.deletion.DO_NOTHING, to='tipoVehiculo.tipovehiculo')),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
    ]
