# Generated by Django 3.1 on 2020-10-11 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('asesor', models.ForeignKey(db_column='asesor', on_delete=django.db.models.deletion.DO_NOTHING, to='empleado.empleado')),
                ('cliente', models.ForeignKey(db_column='cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente')),
            ],
            options={
                'db_table': 'cita',
            },
        ),
    ]
